feat(action): move preflight steps to custom deploy action
moneymeets/action-ecs-deploy pull request #15
Opened 2024-08-16 08:27 UTC by IamAbbey

2024-08-16 09:34 UTC, felix11h reviewed
Just a change in the naming of the step, looks good to me otherwise!

2024-08-16 09:34 UTC, felix11h commented on action.yml
> +      id: deploy-definition-and-run-preflight
Probably _task_ definition missing in the name here. How about
```suggestion
      id: deploy-preflight-task-definition-and-run-task
```
?

2024-08-19 07:05 UTC, marns93 requested changes
In general it looks good to me. Just smaller things. We agreed on removing quotes if they are not needed.
Did you test the changes? Perhaps you can link the pipelines in this PR?

2024-08-19 07:05 UTC, marns93 commented on action.yml
> +    default: "true"
```suggestion
    default: true
```

2024-08-19 07:05 UTC, marns93 commented on custom-deploy-steps/run-preflight/action.yml
> +description: Get image uri from AWS ECR
Please update

2024-08-19 07:05 UTC, marns93 commented on custom-deploy-steps/run-preflight/action.yml
> +    description: "Preflight task ARN"
```suggestion
    description: Preflight task ARN
```

2024-08-19 07:05 UTC, marns93 commented on custom-deploy-steps/run-preflight/action.yml
> +    description: "ARN of previous task definition revision"
```suggestion
    description: ARN of previous task definition revision
```

2024-08-19 07:05 UTC, marns93 commented on custom-deploy-steps/run-preflight/action.yml
> +    description: "ARN of new task definition revision"
```suggestion
    description: ARN of new task definition revision
```

2024-08-19 07:34 UTC, IamAbbey commented
Test Action Runs
with preflight=true
https://github.com/moneymeets/django-insurance-api-v2/actions/runs/10416562236/workflow 

with preflight=false
https://github.com/moneymeets/django-insurance-api-v2/actions/runs/10416929798/workflow

2024-08-19 07:35 UTC, IamAbbey commented
/rebase

2024-08-19 08:12 UTC, marns93 approved these changes
:+1:

2024-08-19 08:22 UTC, merged