fix(action): fix default value for allow_feature_branch_deployment
moneymeets/action-ecs-deploy pull request #22
Opened 2024-11-22 15:31 UTC by pchorus

Deploying softfair-proxy failed with error  `Error: Invalid value for '--allow-feature-branch-deployment': '' is not a valid boolean.`, see pipeline https://github.com/moneymeets/softfair-proxy/actions/runs/11974446052/job/33386112313.

It turns out that setting the default value for the click command does not work.
In `deploy.yaml` the input `allow_feature_branch_deployment` is not required.
When it is used in in call `poetry run actions_helper ecs-deploy` the value for `--allow-feature-branch-deployment` is an empty string. So the empty string is passed to the click function and the default value defined by `@click.option("--allow-feature-branch-deployment", type=bool, default=False)` is never in charge since empty string is passed.

The solution is to set a default value of `false` for `allow_feature_branch_deployment` in the `action.yml` the same way as it is done already for `desired_count`.

To avoid confusion @mm-matthias and I suggest to remove default values from `@click.option`s since they are never relevant anyways.

2024-11-22 15:57 UTC, mm-matthias approved these changes
I'm fine with the changes, but I am not an action-ecs-deploy expert and did no testing.

2024-11-25 06:58 UTC, windwinkel commented
@pchorus In the `deploy.yaml`, shouldn't the parameter made required then as well?

2024-11-25 07:03 UTC, pchorus commented
> @pchorus In the `deploy.yaml`, shouldn't the parameter made required then as well?

No, the parameter should be optional so that the parameter can be omitted where the GitHub Action is used.
And this is already the case for all calling code, e.g. here: https://github.com/moneymeets/softfair-proxy/blob/655f03c0506b5eb9a0e08469eb242c621429f4e5/.github/workflows/deploy.yml#L25.

2024-11-25 07:45 UTC, marns93 requested changes
I think we can get rid of the defaults and make the inputs required.
I've prepared a PR https://github.com/moneymeets/moneymeets-pulumi/pull/734.

I'm fine with removing the defaults from the Python script, it was helpful for local testing, but we can set it explicitly.

So in my opinion we should merge and deploy the PR in moneymeets-pulumi and update this PR to remove the defaults + set `required: true` for `allow_feature_branch_deployment`.

2024-11-25 07:55 UTC, pchorus commented
> I think we can get rid of the defaults and make the inputs required. I've prepared a PR [moneymeets/moneymeets-pulumi#734](https://github.com/moneymeets/moneymeets-pulumi/pull/734).
> 
> I'm fine with removing the defaults from the Python script, it was helpful for local testing, but we can set it explicitly.
> 
> So in my opinion we should merge and deploy the PR in moneymeets-pulumi and update this PR to remove the defaults + set `required: true` for `allow_feature_branch_deployment`.

Alright, since the deployment.yaml files are distributed via Pulumi, your suggestion is even better. I remove the optional values and their defaults. 👍🏻

2024-11-25 12:24 UTC, marns93 approved these changes

2024-11-25 13:11 UTC, pchorus commented
/rebase

2024-11-25 13:12 UTC, merged